--
-- Table structure for table cargo
--

DROP TABLE IF EXISTS cargo;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE cargo (
  id_cargo int NOT NULL IDENTITY,
  nombre varchar(80) NOT NULL,
  PRIMARY KEY (id_cargo)
);

--
-- Dumping data for table cargo
--

/*!40000 ALTER TABLE cargo DISABLE KEYS */;
SET IDENTITY_INSERT cargo OFF;
INSERT INTO cargo VALUES
  ('Rector'),
  ('Vicerrector Academico'),
  ('Jefe de área'),
  ('Secretario(a) general'),
  ('Conserje'),
  ('Chofer'),
  ('Director(a) de área'),
  ('Decano'),
  ('Vicerrector de Investigación'),
  ('Presidente de área'),
  ('Secretario(a) de área'),
  ('Coordinador de área'),
  ('Miembro');
SET IDENTITY_INSERT cargo ON;

DROP TABLE IF EXISTS autorizacion;
CREATE TABLE autorizacion (
  id_autorizacion int NOT NULL identity(1,1),
  resumen varchar(50) NOT NULL,
  descripcion text ,
  id_cargo int NOT NULL,
  PRIMARY KEY (id_autorizacion),
  CONSTRAINT fk_autorizacion_Cargo FOREIGN KEY (id_cargo) REFERENCES cargo (id_cargo)
);

--
-- Dumping data for table autorizacion
--

/*!40000 ALTER TABLE autorizacion DISABLE KEYS */;
INSERT INTO autorizacion (resumen, descripcion, id_cargo) VALUES 
  ('Emision de solicitud ','El jefe de area aprueba la emisión de una solicitud',1),
  ('Aprobacion de solicitud','El director financiero autoriza la validez de una solicitud',2),
  ('Emision de orden de compra','El director financiero autoriza la emision de la orden de compra al proveedor',2);



--
-- Table structure for table personal
--

DROP TABLE IF EXISTS personal;
CREATE TABLE personal (
  id_personal int NOT NULL IDENTITY,
  nombre varchar(80) NOT NULL,
  DNI char(8) NOT NULL,
  id_cargo int NOT NULL,
  PRIMARY KEY (id_personal),
  CONSTRAINT fk_personal_cargo FOREIGN KEY (id_cargo) REFERENCES cargo (id_cargo)
);
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table personal
--

INSERT INTO personal(nombre, DNI, id_cargo) VALUES 
  ('Juan Perez','71661497',1),
  ('Raul Salinas','84563214',2),
  ('Alberto Salas','75684235',3),
  ('Karla Rojas','45621478',1),
  ('Carlos Lopez','75621465',2),
  ('Alvaro Iglesias','69854752',3),
  ('Miguel Rojas','47618951',1),
  ('Luiz Meza','63256271',2),
  ('Marin Kennsley','13772524',2),
  ('Sibley Kisby','31434727',1),
  ('Agathe Bridgens','20239060',1),
  ('Patrizius Juleff','78030605',2),
  ('Beilul Bairnsfather','12747701',2),
  ('Aura Evershed','85825792',3),
  ('Den Purcell','31289418',3),
  ('Daphna Midford','89075288',3),
  ('Jaime Sotworth','99488823',2),
  ('Lyndell Roe','34629990',3),
  ('Austen Gilbart','26160640',2),
  ('Slade Pele','05436069',3),
  ('Brennan Spatig','32311449',3),
  ('Courtnay Poltun','90539072',1),
  ('Hyacinthie Quiddihy','56400385',3),
  ('Donavon Barnwill','43402823',2),
  ('Essa Hearne','26757863',3),
  ('Aron Vannet','50997027',1),
  ('Ced Purrier','08165767',3),
  ('Tressa Kineton','58196801',1),
  ('Dwayne Macieja','14696224',2),
  ('Nikolos Rape','22241098',2),
  ('Tedra Spriggs','17438338',3),
  ('Hill Pic','39356249',1),
  ('Quent OHartnett','64260697',1),
  ('Alexio Kryszka','61259179',1),
  ('Katina Waison','92564991',2),
  ('Eleanora Dautry','63090950',1),
  ('Drugi Roja','94936601',2),
  ('Devonne Petrashkov','90106529',1),
  ('Elianore Baignard','76879137',2),
  ('Jilleen Pretswell','43048758',3),
  ('Gideon Gazey','23062036',3),
  ('Curcio Partkya','39986080',2),
  ('Agustin Roddick','46867492',2),
  ('Trenna Blackburne','70468551',1),
  ('Walsh Saunter','95088458',3),
  ('Abe Manville','06526327',1),
  ('Lexis Mowles','03337957',1),
  ('Felipe Dengel','78354286',3),
  ('Gardie Somerscales','03377689',1),
  ('Nanni Bartlomiejczyk','79641143',1),
  ('Arri Barsam','53877848',3),
  ('Galina Phonix','17946992',2),
  ('Tabby Craigie','34033987',3),
  ('Leisha Nulty','42375960',3),
  ('Leticia Wooffinden','23506091',2),
  ('Delcina Gantzman','99341715',1),
  ('Cassie Deavall','03011019',1),
  ('Ludvig Haugh','46493053',3),
  ('Martha Fawke','05551015',3),
  ('Arlin Antoniat','93853102',3),
  ('Rosella de Najera','09105336',1),
  ('Clay Rowan','64671332',1),
  ('Allen Eliyahu','47180332',3),
  ('Nadean Brader','15524923',3),
  ('Max Picford','97397790',3),
  ('Kip Tudbald','97553267',3),
  ('Sutton Fitchet','92383120',3),
  ('Arline Dengate','76031487',3),
  ('Fae Volett','45619215',1),
  ('Jammal Roberson','84781229',3),
  ('Vin Balharry','43482462',2),
  ('Kris Luckings','40958953',2),
  ('Ferne Rambaut','74825863',1),
  ('Bettye Gillum','72734278',2),
  ('Roselle Dobbinson','37212229',3),
  ('Vale Baxter','86390841',1),
  ('Anabella Scrange','43844548',2),
  ('Derward Cardoe','40091871',3),
  ('Lela Iacovaccio','44168725',1),
  ('Joete Littrik','70347891',2),
  ('Courtney Morcomb','78583485',1),
  ('Enrichetta Pickerill','21724972',3),
  ('Adolf Jeaycock','91417556',1),
  ('Glynis Scole','87278299',3),
  ('Beckie Barthrop','42028420',1),
  ('Corina Farnan','45383957',3),
  ('Derron Stirtle','49251151',1),
  ('Gladys Gutridge','22621697',1),
  ('Westbrook Bulger','37052978',2),
  ('Lauritz MacClenan','74045187',3),
  ('Pedro Tillett','73527895',3),
  ('Amy Veeler','54040639',1),
  ('Son Wych','70125618',3),
  ('Rosa Croce','76930048',3),
  ('Vivi Gallager','12380849',1),
  ('Brianna Bazley','43612419',2),
  ('Rosemarie Falloon','12411939',3),
  ('Dalston Hembery','96364525',1),
  ('Laural Bofield','88867053',2),
  ('Simeon Chaffyn','18213596',2),
  ('Sawyer Eilers','13578552',2),
  ('Joe Bourchier','42920503',1),
  ('Anatole Sappy','99915732',3),
  ('Wayland Volage','01748017',1),
  ('Bevan Madrell','28473852',2),
  ('Derril Kidds','88495534',3),
  ('Gaultiero Leverett','51252494',3),
  ('Deane Fann','84835421',2),
  ('Maxy Iacobassi','28647682',3),
  ('Conny Morch','53332705',1),
  ('Johny Muckian','32816690',3),
  ('Esme McGready','51174016',2),
  ('Elly Gianolo','77060457',1),
  ('Jules Wilfing','99108632',2),
  ('Jessamine Chippin','02032403',1),
  ('Celina Burrill','56521925',2),
  ('Hadrian Mongain','74779093',1),
  ('Byram Sneesby','60551778',3),
  ('Andrus Nosworthy','85648558',1),
  ('Raeann Elijahu','36239817',1),
  ('Malachi Gillson','14577035',2),
  ('Beverly Meneer','06531925',3),
  ('Catharine Mattack','08228199',2),
  ('Gwyn Sang','40547660',1),
  ('Hebert Keelan','78661083',3),
  ('Colas Ebbins','72887663',3),
  ('Welch Titmuss','97299573',3),
  ('Itch Feaver','69516512',2),
  ('Lyndel Kenzie','78384902',2),
  ('Elwira Lepope','31827617',2),
  ('Sonnie Rotherham','51735959',1),
  ('Bryana McSperrin','54892652',2),
  ('Chuck Bateman','89060767',2),
  ('Fransisco Baraja','94363244',3),
  ('Mathilde Goldin','22456711',1),
  ('Quentin Harmond','22251747',3),
  ('Kacy Tanswill','20442974',1),
  ('Shamus Seifert','85574829',3),
  ('Carver Steanson','98170868',3),
  ('Eilis Cusick','07524186',1),
  ('Gerry Bosket','72446501',2),
  ('Raimundo Standeven','96811026',3),
  ('Ruddy Upcott','32662944',1),
  ('Cordell Craine','63620514',2),
  ('Willi Vanne','46440926',3),
  ('Oneida Croshaw','41062815',3),
  ('Antonia Tillard','62627150',1),
  ('Hilton Symcox','41890369',3),
  ('Gayelord Bastard','71758322',3),
  ('Lincoln Geering','25424238',3),
  ('Rosalinda Hullin','93693613',1),
  ('Goober Kilty','45709223',3),
  ('Mavis Westover','03003038',1),
  ('Tommie Heaviside','32962705',2),
  ('Cathryn Jeff','80295603',3),
  ('Bev Cordle','15247055',3),
  ('Torrance Thrasher','45557390',1),
  ('Herschel Gauntlett','81633550',3),
  ('Georgie Kings','47656674',1),
  ('Zachary Mazillius','33871670',3),
  ('Shelagh Nevitt','70279693',3),
  ('Alvira Cabell','61657434',1),
  ('Celeste Bourley','64342353',1),
  ('Lena Morrieson','10604728',2),
  ('Holly-anne Sobey','46312068',2),
  ('Barbey Whiteman','64004064',3),
  ('Dennis Rance','80611270',2),
  ('Mannie McNelly','79502315',3),
  ('Clary Yacob','26858553',3),
  ('Fredek Waistell','90564469',2),
  ('Cayla Gonning','70993108',1),
  ('Woodrow Sabater','51000310',2),
  ('Normie Lapides','90979584',2),
  ('Odetta Fayers','93126087',3),
  ('Lucien Sugg','04850526',1),
  ('Daveen Klimek','49398537',3),
  ('Marjy Duffield','66062325',3),
  ('Joelie Redford','68600031',1),
  ('Florry Kiltie','82040439',1),
  ('Elspeth Paulillo','42806927',1),
  ('Sharla Ralling','80454425',3),
  ('Hollyanne Lambal','78056494',3),
  ('Colleen Gudde','96387647',2),
  ('Emmalynne Buckner','67232107',2),
  ('Donny Frangello','23594751',3),
  ('Torrey Gorini','31659986',2),
  ('Nari Spatari','86937121',2),
  ('Alaster Prawle','68554300',2),
  ('Shandie Habbeshaw','24971657',2),
  ('Rorie Decayette','64789817',1),
  ('Cinnamon Lusher','85554948',3),
  ('Oran Coetzee','26265318',3),
  ('Maynard Blackboro','22094148',1),
  ('Nixie Sisey','57995104',1),
  ('Carin Marini','62344271',2),
  ('Kathie Spurdens','25884549',1),
  ('Cortie Kinworthy','91865537',3),
  ('Gram Barcroft','33131903',2),
  ('Hallie Flawn','14575823',3),
  ('Kris Draysey','87534354',3),
  ('Bary Butterley','23847900',2),
  ('Paddie Cleyburn','11793288',1),
  ('Arvie Jacobowitz','44305022',3),
  ('Roderick Preshaw','98088323',1),
  ('Katerine Paulet','51377661',3),
  ('Charlene Goldsworthy','38091172',3),
  ('Christos Kerrod','87906576',1),
  ('Natasha Jenkin','11802875',3),
  ('Sileas Angove','93493152',3),
  ('Wallace Bridger','69636791',1),
  ('Tiena Baythorp','81546164',1),
  ('Kristin Truckett','06728018',2),
  ('Alberto Tuckwood','13720634',2),
  ('Garik Langan','83730108',2),
  ('Yanaton Torbard','10625482',2),
  ('Janela Emilien','88820232',3),
  ('Leeanne McCully','12285766',2),
  ('Staffard Perks','56054386',1),
  ('Cassandra Dockree','44641315',3),
  ('Gill Frayne','88456776',1),
  ('Tandi Seale','44471645',1),
  ('Roddie Chatelain','97363231',1),
  ('Sofia Oneill','56008458',1),
  ('Shoshana Blay','76004144',3),
  ('Beck Attawell','98762716',3),
  ('Marcile Alasdair','11727651',2),
  ('Perla Dundridge','63888193',3),
  ('Kip Viger','08545454',2),
  ('Junie Ropars','02992415',3),
  ('Orazio Swapp','74870297',3),
  ('Elfie Dainton','02226878',1),
  ('Wandis Edon','10652643',3),
  ('Michail Cord','93693304',2),
  ('Westbrooke Polendine','49551072',1),
  ('Christian Keller','65026536',3),
  ('Gregoire Killingback','18386314',3),
  ('Kassie Cavozzi','84420909',1),
  ('Shermie Foulks','42593441',1),
  ('Clint Brandon','35216562',2),
  ('Stephie Hindrick','19445823',1),
  ('Germayne Massy','44075362',2),
  ('Marnie Booton','44888172',2),
  ('Emyle Gilding','62927722',1),
  ('Aurlie Tschierasche','15812416',1),
  ('Maximo Rankling','11331227',2),
  ('Darice Trime','64089858',1),
  ('Jerad Dunton','58095384',2),
  ('Leo Gerrie','44056692',2),
  ('Neron Gier','27042507',1),
  ('Ashlen Jaycock','31976402',2),
  ('Graham Tewes','15349047',1),
  ('Otto Houtby','03347708',1),
  ('Jemmy Sansum','75628037',2),
  ('Hyman Olphert','63444458',2),
  ('Karin Barles','37765486',2),
  ('Delora Blythe','97928700',1),
  ('Sammy Hovie','53663909',3),
  ('Renelle Rawstorn','62437771',1),
  ('Virgie Fritchley','34591939',3),
  ('Pietra Chrippes','66313256',2),
  ('Marion Bronot','01593794',2),
  ('Rozanna Lugden','17635466',2),
  ('Reinaldos Jakubowski','20844171',3),
  ('Nicol Wickins','44995737',2),
  ('Kirsten Pyner','70449905',2),
  ('Suzi Gifkins','74327246',1),
  ('Isabeau Maasze','59100155',3),
  ('Skyler Swan','54631986',3),
  ('Raphaela Gooms','46841089',2),
  ('Annette Duchasteau','80123770',3),
  ('Townie McKiernan','56841670',1),
  ('Susette Meadley','80527106',1),
  ('Antoni Menier','46685492',2),
  ('Trstram Poolman','55832159',1),
  ('Jermayne Stoffler','53358829',1),
  ('Mufinella Falkus','16665614',3),
  ('Shelba MacDiarmid','89634685',3),
  ('Celinda Backe','36312745',3),
  ('Durant Durnford','81692498',2),
  ('Niccolo Bennen','33758772',2),
  ('Lotti Carwardine','24963254',3),
  ('Ravi Alvares','42588739',1),
  ('Marshal Brookshaw','71150695',2),
  ('Merrel Mundford','40541210',3),
  ('Flint Moule','03455540',3),
  ('Tucker Sheryne','68989640',1),
  ('Elias Marzelli','77255452',2),
  ('Duke Carlucci','51516015',3),
  ('Neille McKirton','90335009',1),
  ('Della Reily','83668676',1),
  ('Yulma Forsyde','83814132',3),
  ('Dedra McGiffin','78122833',2),
  ('Silvano Tift','53237152',1),
  ('Florence Rollin','08050887',1),
  ('Rachelle Jacombs','42779811',3),
  ('Ilyse Renols','13952040',1),
  ('Dorelle Wescott','13470808',2),
  ('Constantine Schruurs','43976455',1),
  ('Robers Proudlove','88992627',1),
  ('Colman Limb','86164565',1),
  ('Nathanael Morstatt','79787394',1),
  ('Vaughan McSporrin','03755652',1),
  ('Eadith Pickover','93641381',2),
  ('Nisse Quipp','25475467',2),
  ('Alexandr Gerasch','87353885',2),
  ('Vidovic Bricksey','63299207',2),
  ('Micki Domenget','01088532',3),
  ('Christyna Cansdale','30526638',3),
  ('Demeter Hackey','67879116',3),
  ('Susie Gregson','56589689',2),
  ('Ollie Peat','10516359',3),
  ('Amelie Angelini','82079178',2),
  ('Traci Trusty','62301439',1),
  ('Beau Bernier','52893246',1),
  ('Kathrine Dilston','26365438',3),
  ('Kirstyn Casel','21042401',3),
  ('Marlane Gye','30759644',2),
  ('Gusta Murfin','73376935',1),
  ('Stephi Vasey','00531832',3),
  ('Mandel Dobey','77349394',1),
  ('Helga Leivesley','08640576',3),
  ('Carson Jennions','36075637',1),
  ('Jehanna Giorgiutti','02952250',3),
  ('Kris Dupree','73074559',2),
  ('Louie Bolver','34637878',2),
  ('Mariele McMichell','78896954',3),
  ('Alyda Tomaino','81995714',1),
  ('Zebedee Fairs','64649972',2),
  ('Vanda MacCathay','18732768',2),
  ('Mel Pring','06820376',2),
  ('Melisenda Steere','53440443',1),
  ('Kittie Learoid','72863612',1),
  ('Bernadette Begent','62771006',3),
  ('Alla Methingam','11023267',2),
  ('Forrest Forgan','45149159',3),
  ('Nester Sylvester','51793911',2),
  ('Sydney Congrave','51226311',1),
  ('Stepha Jovis','17927311',1),
  ('Harbert MacNamara','46633687',3),
  ('Violette Corradengo','70188811',2),
  ('Tressa Bovaird','54213071',1),
  ('Carey Kilborn','93285389',3),
  ('Lynnett Skentelbury','32772707',2),
  ('Barbabra Burt','83714340',3),
  ('Loraine Garfield','00637178',2),
  ('Stirling Picott','79688787',2),
  ('Ingra Gehrtz','60224545',2),
  ('Ronny Fireman','78793693',3),
  ('Gates Cankett','01599660',2),
  ('Ashlie Hedin','28496816',2),
  ('Park Folliott','34881984',1),
  ('Sadie Simpkin','33843310',3),
  ('Daveta Halhead','76402875',3),
  ('Vic Scragg','43583688',1),
  ('Marlon Ilchuk','78086551',1),
  ('Lynnette Butland','46471668',3),
  ('Barbabra Humpatch','00560192',2),
  ('Miran Wadmore','90931856',3),
  ('Solly Burnsall','97776081',2),
  ('Gunner Ellerington','80055084',1),
  ('Karilynn Dillintone','91699985',1),
  ('Cullen Beningfield','97772097',2),
  ('Ruttger Wadforth','06705135',2),
  ('Elvina Shearstone','86921182',3),
  ('Dana Hurst','57166999',3),
  ('Wyn Treadaway','26498712',3),
  ('Celestine Cutler','41833345',1),
  ('Cleopatra Gilsthorpe','62268418',3),
  ('Jeffie Windram','90994671',1),
  ('Pierre Reynalds','58855995',3),
  ('Chantalle Matthieson','81515289',1),
  ('Stinky Loche','05106021',2),
  ('Nancy Mumbray','68938325',1),
  ('Lemmy Aberdalgy','23421997',1),
  ('Abbe Ackers','58345373',1),
  ('Stephie Androlli','13688034',1),
  ('May Curedale','62471749',2),
  ('Carmelita Leirmonth','29372153',3),
  ('Addie Champerlen','71598695',3),
  ('Kacey Beardon','15317675',3),
  ('Noach Axton','65870824',1),
  ('Cherey Glassborow','52201323',1),
  ('Christoper Peegrem','18362060',1),
  ('Kacie Poure','63381831',2),
  ('Claude Gutherson','67804215',3),
  ('Aeriell Boulder','37106850',2),
  ('Hanson Cassar','02282802',3),
  ('Jarvis Adcocks','55108612',3),
  ('Rosetta Dring','70933339',1),
  ('Flint Agass','18550357',3),
  ('Haroun Feye','49888621',3),
  ('Hallsy Anneslie','32362848',2),
  ('Romain Puffett','03568010',1),
  ('Sheppard de Verson','63360757',2),
  ('Jonathon Gosneye','91713001',2),
  ('Enrichetta Muschette','89018906',2),
  ('Corty Potkin','79231027',2),
  ('Sallee Riggeard','50099632',2),
  ('Pauly Borton','26812068',1),
  ('Antonius Laycock','70437615',1),
  ('Gweneth Cubbon','69865147',2),
  ('Genny Twizell','40686150',3),
  ('Kristin Baggot','51103595',3),
  ('Fredrika Pursehouse','22190625',3),
  ('Stavro Romayne','33684695',2),
  ('Cyndi Kielt','15577004',1),
  ('Cherise Biasotti','66512218',1),
  ('Marc Cassell','97748641',1),
  ('Margarete Jovasevic','10543299',1),
  ('Chad Byers','07168424',3),
  ('Anthe Dolby','77716138',3),
  ('Consuela Segrott','46597760',2),
  ('Agace Abley','70982753',1),
  ('Heloise Ritch','01594673',1),
  ('Alvis Joist','53554127',1),
  ('Lombard Ellson','37137227',3),
  ('Lu Newcomen','52240235',1),
  ('Kathrine Cranstoun','05795101',1),
  ('Jocko Fishlee','33636063',1),
  ('Walsh Braim','12752930',2),
  ('Sadie Kinchington','07485659',3),
  ('Sterne Bilney','36246191',2),
  ('Tory Dumbarton','56845429',1),
  ('Jerrilee Pengilly','54967651',1),
  ('Pincus Domelow','83987336',1),
  ('Gracia Lacoste','38757258',3),
  ('Aveline Hugin','64717966',3),
  ('Isak Folker','05627668',1),
  ('Morgan De Carlo','27571262',2),
  ('Florian Sabathier','92513703',3),
  ('Eugine Kittman','74557553',1),
  ('Standford Holywell','34176866',3),
  ('Chantalle Milkeham','81432584',1),
  ('Morganne Risebarer','56720405',3),
  ('Manfred Paver','18027387',3),
  ('Padgett Terrett','03522174',3),
  ('Ephrayim Delacourt','68231669',1),
  ('Neda Woolbrook','29389771',2),
  ('Morie O. Dare','22510059',1),
  ('Lacey Gouly','79008525',2),
  ('Hobie Fidian','78560905',1),
  ('Nita Burnside','23059680',2),
  ('Kimberley Moakler','61032253',2),
  ('Conan Constable','43007211',3),
  ('Rickie Khomishin','58880679',1),
  ('Allyce Eyre','85201045',1),
  ('Carin Willcot','22337132',3),
  ('Ian Exall','24231968',2),
  ('Stavros Dell Casa','56041997',1),
  ('Paxton Le Bosse','07963788',2),
  ('Ofella Spitaro','15731794',3),
  ('Worden Wellan','87404245',3),
  ('Giraldo Jovic','70657252',1),
  ('Menard Rickards','84576075',2),
  ('Remus Poulney','92440629',3),
  ('Chandler Hintze','15841927',2),
  ('Emmy Sheaber','45050361',1),
  ('Darsey Bignell','26328944',3),
  ('Jimmie Demelt','98067941',2),
  ('Aile Kettlewell','93287181',1),
  ('Sloan McGriele','34887949',3),
  ('Lindon Duke','52105709',3),
  ('Rosina Elletson','53751651',2),
  ('Leicester Sieghart','29985612',1),
  ('Evangelin Starford','09872275',1),
  ('Steven Izkoveski','93474807',3),
  ('Lulita Garces','79178875',2),
  ('Trisha Thrasher','71249540',3),
  ('Merwin Guidone','49173642',1),
  ('Briant Elston','91198695',1),
  ('Brenden Creelman','76950210',3),
  ('Asher Jirick','95570851',1),
  ('Sax Calafate','20961010',1),
  ('Gayle Bonds','49718853',3),
  ('Julian MacCart','70231295',1),
  ('Cam Weight','49360865',3),
  ('Allys Stiles','36952313',2),
  ('Elke Stichall','96894129',1),
  ('Teodoor Jelly','94456820',1),
  ('Terza Skeete','80868697',2),
  ('Court Beddows','82884425',3),
  ('Emmalynn Buie','81189734',3),
  ('Katie Ekkel','96014935',2),
  ('Dylan Adkins','45408375',2),
  ('Frederico Labrone','73336238',3),
  ('Christal Aldrich','47648295',1),
  ('Nappy O. Hegertie','49867723',3),
  ('Cody Lissemore','05226587',3),
  ('Marlena Pergens','57520112',1),
  ('Darcee Muzzi','13039438',3),
  ('Dallas Conkey','08214699',3),
  ('Sullivan Bretland','65404889',2),
  ('Eadith Hunnicutt','96325135',2),
  ('Win Von Oertzen','36890313',3),
  ('Winnie Shervil','27507710',2),
  ('Kerianne Parkman','18649191',1),
  ('Adriane Gass','60138278',3),
  ('Glynis Tilliard','52208214',1),
  ('Rudy Dollard','65166423',1),
  ('Elisabetta Acton','08989193',2),
  ('Beniamino Geldeard','68540374',1),
  ('Mechelle McKeighan','70087673',1),
  ('Carmon Houndesome','01402923',2),
  ('Carlen Winn','72579261',3),
  ('Francis Folds','94540574',3),
  ('Bruis Cradock','18201950',2),
  ('Payton Capinetti','05442034',3),
  ('Layton Colwell','65061070',2);


--
-- Table structure for table proveedor
--

DROP TABLE IF EXISTS proveedor;
CREATE TABLE proveedor (
  id_proveedor int NOT NULL IDENTITY,
  nombre varchar(80) NOT NULL,
  PRIMARY KEY (id_proveedor)
);
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table proveedor
--

/*!40000 ALTER TABLE proveedor DISABLE KEYS */;
INSERT INTO proveedor(nombre) VALUES 
  ('Kuhlman Group'),
  ('Kris Inc'),
  ('Conroy Inc'),
  ('Murazik Inc'),
  ('Schulist, Ratke and Mitchell'),
  ('Maggio-Bergstrom'),
  ('Bayer Group'),
  ('Purdy LLC'),
  ('Brakus, Lebsack and Fadel'),
  ('McLaughlin-McClure'),
  ('Ebert-McClure'),
  ('Braun, Howell and Kassulke'),
  ('Smith-Keeling'),
  ('Moore-Toy'),
  ('Huels, Schamberger and Cremin'),
  ('Lang-Rice'),
  ('Gusikowski, Blanda and Wilderman'),
  ('Koepp, Larkin and Jacobson'),
  ('Kilback LLC'),
  ('Kovacek Group'),
  ('Carroll Inc'),
  ('Ortiz Inc'),
  ('Stiedemann Inc'),
  ('Feeney and Sons'),
  ('Wuckert-Boyle'),
  ('Christiansen, Bradtke and Boehm'),
  ('Goldner and Sons'),
  ('Kovacek Group'),
  ('Langosh-Strosin'),
  ('Rolfson, Crona and Kiehn'),
  ('Shanahan-Kshlerin'),
  ('Heathcote-Osinski'),
  ('Beatty Inc'),
  ('Heathcote Group'),
  ('Champlin, Kiehn and Reinger'),
  ('Vandervort LLC'),
  ('Huel, Bayer and Bode'),
  ('Huel, Jacobson and Muller'),
  ('Hegmann, Bechtelar and Hamill'),
  ('Kling, Murray and Streich'),
  ('Rolfson-Wehner'),
  ('Runolfsdottir Inc'),
  ('Ruecker and Sons'),
  ('Yundt-Leuschke'),
  ('Jenkins-Morissette'),
  ('Lowe and Sons'),
  ('Lubowitz-Kutch'),
  ('Davis Group'),
  ('Reilly-Zieme'),
  ('Kling-Smith'),
  ('Wisoky and Sons'),
  ('Hickle-Rice'),
  ('Turner Group'),
  ('Witting, Renner and Hudson'),
  ('Rau, Stanton and Runolfsdottir'),
  ('Considine-Wehner'),
  ('Barrows and Sons'),
  ('Fadel-Goyette'),
  ('Kilback-O. Connell'),
  ('Keebler-Feil'),
  ('O. Hara, Wiza and Gleichner'),
  ('Lockman, Yost and Baumbach'),
  ('Deckow Group'),
  ('Douglas, Sauer and Bruen'),
  ('Moen, Wolf and Kautzer'),
  ('Rath, Parker and Kreiger'),
  ('Schoen and Sons'),
  ('Abernathy Group'),
  ('Ziemann, Wisozk and Pagac'),
  ('Torphy-Hand'),
  ('Pagac, Stamm and Koepp'),
  ('O. Hara-Monahan'),
  ('Ziemann, Howe and Haley'),
  ('Hammes LLC'),
  ('Quigley, Cartwright and Stokes'),
  ('Franecki-Schuster'),
  ('Lueilwitz, Yundt and Tillman'),
  ('Hand-Hermann'),
  ('Bailey, Grimes and Cruickshank'),
  ('Armstrong-Connelly'),
  ('Pouros, Greenfelder and Monahan'),
  ('O. Connell, Gislason and Volkman'),
  ('Quitzon Group'),
  ('VonRueden-Schmidt'),
  ('Dooley, Grimes and Gleason'),
  ('Walter-Steuber'),
  ('Kilback Group'),
  ('Mueller, Jakubowski and Anderson'),
  ('Bauch-Kuhlman'),
  ('Padberg LLC'),
  ('Steuber and Sons'),
  ('Strosin Inc'),
  ('Beatty-Hammes'),
  ('Roberts LLC'),
  ('Kovacek, Boyer and Price'),
  ('Schoen, Dicki and Steuber'),
  ('Bartell-O. Kon'),
  ('Price, Torphy and Barrows'),
  ('Ernser, Dickens and Quigley'),
  ('Metz, Bernier and Ebert'),
  ('Stanton-Becker'),
  ('Willms Inc'),
  ('Kuhic-Pfannerstill'),
  ('Keeling, Beatty and Kihn'),
  ('Bruen, McDermott and Schamberger'),
  ('Mertz, Upton and Parker'),
  ('Kreiger, Barton and Hand'),
  ('Daniel-Murazik'),
  ('Jakubowski, Schinner and Wehner'),
  ('Ankunding LLC'),
  ('Shields-O. Kon'),
  ('Olson, Russel and Marks'),
  ('Gorczany-Huels'),
  ('Parisian LLC'),
  ('Haag and Sons'),
  ('Labadie Inc'),
  ('Lemke and Sons'),
  ('Nienow-Mayer'),
  ('Bernier Group'),
  ('Donnelly, Treutel and Collier'),
  ('Hegmann, O. Kon and Huel'),
  ('Trantow-Gleason'),
  ('Rau Group'),
  ('Corwin and Sons'),
  ('Ritchie LLC'),
  ('Hane LLC'),
  ('Reichert-Trantow'),
  ('Sporer Group'),
  ('Kerluke LLC'),
  ('Zulauf, Bins and Rutherford'),
  ('Haag-Rau'),
  ('Hilpert, Doyle and Kuhn'),
  ('Pagac, Murray and Maggio'),
  ('Hansen, Weber and Schuster'),
  ('Runolfsdottir-Dooley'),
  ('Feest Group'),
  ('Spinka-Durgan'),
  ('Ward and Sons'),
  ('Smith Inc'),
  ('Bahringer, Braun and McGlynn'),
  ('Kerluke, Boehm and Gerhold'),
  ('Friesen LLC'),
  ('Mertz, Parker and Hammes'),
  ('Mitchell-Walker'),
  ('Steuber-Kub'),
  ('Gaylord-Johnson'),
  ('O. Keefe-Smitham'),
  ('Olson LLC'),
  ('Mitchell Inc'),
  ('Jacobi, Bosco and Fritsch'),
  ('Durgan Group'),
  ('Hamill, Balistreri and Sanford'),
  ('Flatley, Flatley and Schumm'),
  ('Bailey-Kemmer'),
  ('Cruickshank, Fahey and Ferry'),
  ('Leuschke Inc'),
  ('Bradtke, Tillman and Keeling'),
  ('Grimes, Ledner and Jacobs'),
  ('Haag Inc'),
  ('Luettgen-Mayert'),
  ('Borer, Gorczany and Skiles'),
  ('Feest-Abernathy'),
  ('Osinski LLC'),
  ('Batz-Baumbach'),
  ('Kiehn-Glover'),
  ('Dietrich, Murphy and Kohler'),
  ('Tremblay, Hickle and Parisian'),
  ('Schmeler, Littel and Smitham'),
  ('Volkman-Ankunding'),
  ('Ratke, Sauer and Bogan'),
  ('Osinski-Reilly'),
  ('Abshire-Hartmann'),
  ('Robel Inc'),
  ('Zieme, Toy and Hilll'),
  ('Gislason-Davis'),
  ('Rowe, Hirthe and Sauer'),
  ('Gutmann, Daniel and Koepp'),
  ('Prosacco, Bradtke and Powlowski'),
  ('Weimann-Hansen'),
  ('Halvorson, Trantow and McLaughlin'),
  ('Hartmann, McGlynn and Hamill'),
  ('Emard-Lehner'),
  ('Flatley Group'),
  ('Schaefer, Ondricka and O. Reilly'),
  ('Erdman-Nolan'),
  ('Graham Inc'),
  ('Huel-Lebsack'),
  ('Effertz, Kuhic and White'),
  ('Kling and Sons'),
  ('Pfeffer and Sons'),
  ('Fritsch Inc'),
  ('Reinger-Wuckert'),
  ('Kuhic, Aufderhar and Muller'),
  ('Wuckert, Pfannerstill and Corwin'),
  ('Kling-Heidenreich'),
  ('Lynch and Sons'),
  ('Veum-Mann'),
  ('Boyle LLC'),
  ('Ullrich-Swaniawski'),
  ('King-Watsica'),
  ('Schmeler-Reynolds'),
  ('Carroll Group'),
  ('Heaney, Stark and Herman'),
  ('Connelly-Nolan'),
  ('Reynolds-Fritsch'),
  ('Runte, Leffler and Cassin'),
  ('Murphy, Marquardt and Bernhard'),
  ('Hansen-Sipes'),
  ('Osinski, Frami and Tillman'),
  ('McGlynn-Botsford'),
  ('Quigley, Erdman and Runolfsson'),
  ('Morar-Dickens'),
  ('Walter Group'),
  ('Stokes, Kulas and Tillman'),
  ('Braun Group'),
  ('Bednar, Toy and Marquardt'),
  ('Sanford Group'),
  ('Marvin, Kuhic and Jerde'),
  ('Wilkinson, Sauer and Medhurst'),
  ('Kuhic Inc'),
  ('Romaguera, Hintz and Kuvalis'),
  ('Sauer-Kirlin'),
  ('Hermann-Runolfsdottir'),
  ('Wilkinson, Lemke and Leannon'),
  ('Considine LLC'),
  ('Mills-Okuneva'),
  ('Johns, Connelly and Kub'),
  ('Waelchi, Mayert and Shanahan'),
  ('Ortiz-Williamson'),
  ('Conn-Brakus'),
  ('Gutmann, Nitzsche and Padberg'),
  ('Hauck-McKenzie'),
  ('Zemlak, Bayer and Lebsack'),
  ('Hessel, Hagenes and Bayer'),
  ('Beahan, Wehner and Considine'),
  ('Willms LLC'),
  ('Marks, Casper and Miller'),
  ('Kub-Ritchie'),
  ('Hoppe Group'),
  ('Boyer, Donnelly and Berge'),
  ('Dicki, Toy and Keeling'),
  ('Crooks-Kirlin'),
  ('Oberbrunner, Gaylord and Turner'),
  ('Powlowski, Johnston and Graham'),
  ('Ernser and Sons'),
  ('Bashirian Inc'),
  ('Simonis Inc'),
  ('Marvin, Torp and Fadel'),
  ('Yost, Fadel and Dietrich'),
  ('Sporer, Larkin and Robel'),
  ('Skiles Group'),
  ('Connelly-Schulist'),
  ('Roberts and Sons'),
  ('Wunsch Group'),
  ('Goldner Group'),
  ('Wolf-Mann'),
  ('Kemmer, Beahan and Kub'),
  ('Bode, Grant and Sporer'),
  ('Macejkovic-Lockman'),
  ('Jast Inc'),
  ('Koepp and Sons'),
  ('Metz-Predovic'),
  ('Dare Group'),
  ('Dietrich, Mertz and Konopelski'),
  ('Turcotte and Sons'),
  ('Towne, Brekke and Upton'),
  ('Kiehn, Turner and Hansen'),
  ('Farrell, Mitchell and Lueilwitz'),
  ('Mayer Inc'),
  ('Kshlerin LLC'),
  ('Jast, Weimann and Wyman'),
  ('Hahn, Baumbach and Kuhlman'),
  ('Conn, Maggio and Hane'),
  ('Schultz-Windler'),
  ('Upton-Johnson'),
  ('Reynolds-Pagac'),
  ('Hammes, Schneider and Dooley'),
  ('Dicki-Okuneva'),
  ('Rohan-Ritchie'),
  ('Kuhn-Glover'),
  ('Marvin-Gislason'),
  ('Ledner-Ward'),
  ('Hahn, Keeling and Macejkovic'),
  ('Nikolaus-Ullrich'),
  ('Towne Inc'),
  ('Jones, Huel and Gibson'),
  ('Morissette, Shields and Stroman'),
  ('Rogahn, Kilback and Jacobs'),
  ('Dare-Lindgren'),
  ('Ankunding, Flatley and Stroman'),
  ('Gorczany, Lowe and Jaskolski'),
  ('Monahan Inc'),
  ('Leffler, Upton and Bosco'),
  ('Morar-Koss'),
  ('Jacobi-Block'),
  ('Okuneva-Langosh'),
  ('Jones, Glover and Weimann'),
  ('Barton and Sons'),
  ('Medhurst-Reichel'),
  ('Schultz-Corwin'),
  ('Kub, Rath and Howe'),
  ('Rempel LLC'),
  ('Grant, Breitenberg and Ryan'),
  ('Dickinson Group'),
  ('Crooks, Nienow and Boyer'),
  ('Hyatt-Wunsch'),
  ('Boyle, Schaden and Little'),
  ('Hermiston-Parker'),
  ('Yost and Sons'),
  ('Considine and Sons'),
  ('Morissette-Hodkiewicz'),
  ('Wunsch, Mitchell and Terry'),
  ('Rowe Inc'),
  ('Roob, Block and Kozey'),
  ('Aufderhar and Sons'),
  ('Hilpert Group'),
  ('Spinka-Larson'),
  ('Kohler Inc'),
  ('Schiller Inc'),
  ('Langosh, Bechtelar and Hartmann'),
  ('Zieme-Koss'),
  ('Huels-Hansen'),
  ('Wunsch-Reichel'),
  ('Waters Group'),
  ('Boyer-Collins'),
  ('Boyle-Blick'),
  ('Bashirian, Witting and Dickens'),
  ('Sawayn-Zieme'),
  ('Sanford-Murazik'),
  ('Schimmel LLC'),
  ('Lubowitz LLC'),
  ('Padberg, McCullough and Grimes'),
  ('Witting-D. Amore'),
  ('Douglas, Harvey and Hessel'),
  ('Koss-Wisozk'),
  ('Hessel-Frami'),
  ('Crist-Satterfield'),
  ('Wiza, Hessel and Gutkowski'),
  ('Dickinson LLC'),
  ('Parker, Schultz and Schuppe'),
  ('Johnson, Mante and Schumm'),
  ('Waelchi-Crona'),
  ('Williamson LLC'),
  ('Bailey, Mayer and Abshire'),
  ('McGlynn and Sons'),
  ('Yost Group'),
  ('Brakus, Bruen and Abernathy'),
  ('Ondricka-Schmeler'),
  ('Romaguera-Wilkinson'),
  ('Abernathy Group'),
  ('Fisher-Moore'),
  ('Conroy, Hamill and Boehm'),
  ('Ferry-Conn'),
  ('Rodriguez Group'),
  ('Boyer and Sons'),
  ('Nikolaus, McClure and Gislason'),
  ('Nader-Crooks'),
  ('Pouros Group'),
  ('Vandervort LLC'),
  ('Mosciski-Steuber'),
  ('Farrell-Nader'),
  ('Zulauf and Sons'),
  ('Davis LLC'),
  ('Miller-Gleason'),
  ('Kuhlman LLC'),
  ('Nitzsche LLC'),
  ('Fadel-Waters'),
  ('Carroll-Schuster'),
  ('Reichert Group'),
  ('Halvorson Inc'),
  ('Reichert and Sons'),
  ('Haag-Ortiz'),
  ('Abbott LLC'),
  ('Abshire LLC'),
  ('Rosenbaum-Schmidt'),
  ('Hagenes and Sons'),
  ('Kertzmann-Anderson'),
  ('Paucek LLC'),
  ('Hegmann and Sons'),
  ('Bayer-Waters'),
  ('Hahn, Kautzer and Bradtke'),
  ('Dach Inc'),
  ('Parisian-Keeling'),
  ('Murray LLC'),
  ('Kuhn, Leuschke and Weimann'),
  ('Leuschke, McClure and Sauer'),
  ('Kling Inc'),
  ('Bayer, Kilback and Reichel'),
  ('Emard-Dicki'),
  ('Leffler-Johnson'),
  ('Glover-Gibson'),
  ('Hilpert, Stiedemann and Heaney'),
  ('Brekke Inc'),
  ('Schuster, Dickinson and Dooley'),
  ('Rowe LLC'),
  ('Watsica Inc'),
  ('Walsh and Sons'),
  ('Runolfsson-Reichel'),
  ('Farrell and Sons'),
  ('Shields, Ortiz and Ebert'),
  ('Rau, Schuster and Kuphal'),
  ('Schaden Inc'),
  ('Heathcote-Tillman'),
  ('Ortiz-Wiegand'),
  ('Murazik-Kub'),
  ('Von, Bartoletti and Flatley'),
  ('O. Reilly-Mayert'),
  ('Lockman Group'),
  ('Mann, Berge and O. Connell'),
  ('Kirlin Inc'),
  ('Emard-Schaefer'),
  ('Christiansen-Rolfson'),
  ('Funk, Stiedemann and Kemmer'),
  ('Hilll Inc'),
  ('Olson, Brakus and Anderson'),
  ('Shanahan Group'),
  ('Sanford-Roberts'),
  ('Feeney, Osinski and Beier'),
  ('Reichert-Dare'),
  ('Douglas-Murphy'),
  ('Ritchie-Gutkowski'),
  ('Dicki Inc'),
  ('Brown-Ondricka'),
  ('Feest LLC'),
  ('Bartoletti-Greenholt'),
  ('Mills-Hauck'),
  ('Veum, Bogan and Casper'),
  ('Ondricka and Sons'),
  ('Vandervort Group'),
  ('Flatley Group'),
  ('Grady, Beer and Morar'),
  ('Mraz-Kub'),
  ('Bayer, Muller and Shields'),
  ('Erdman LLC'),
  ('Batz LLC'),
  ('Hegmann, Jacobson and Kling'),
  ('Lynch Inc'),
  ('Bechtelar, Heaney and Pfannerstill'),
  ('King, Schinner and Schmeler'),
  ('Cremin-Kassulke'),
  ('Emmerich, Brown and Ortiz'),
  ('Breitenberg Group'),
  ('Mayert-Collier'),
  ('Pacocha and Sons'),
  ('Mayer, Smitham and Parker'),
  ('Ferry-Rippin'),
  ('Windler and Sons'),
  ('Legros, Monahan and Kuphal'),
  ('Quigley-Dickinson'),
  ('Klein, Wolf and Simonis'),
  ('Hayes, Thompson and Gusikowski'),
  ('Davis-Goldner'),
  ('Armstrong-Kirlin'),
  ('Mann and Sons'),
  ('Schulist-Predovic'),
  ('Osinski-Mohr'),
  ('Goodwin, McKenzie and Walsh'),
  ('Kassulke-Christiansen'),
  ('Mertz, Dickens and Bogisich'),
  ('Medhurst Group'),
  ('Wolf-Bashirian'),
  ('Bernhard, Wehner and Bosco'),
  ('Runolfsdottir-Schiller'),
  ('Grant-Kemmer'),
  ('Bartell Inc'),
  ('Feest-Pfeffer'),
  ('Schultz-Price'),
  ('Konopelski, Goyette and Halvorson'),
  ('Thompson Group'),
  ('Bernier Inc'),
  ('Rogahn, Wyman and Lynch'),
  ('Purdy, Gibson and Tillman'),
  ('Schuster, Flatley and Rowe'),
  ('Funk and Sons'),
  ('Bernier LLC'),
  ('Kihn LLC'),
  ('Towne, Harvey and Kuhn'),
  ('Williamson-Von'),
  ('Nikolaus-West'),
  ('Kuphal Inc'),
  ('O. Keefe and Sons'),
  ('Strosin and Sons'),
  ('Haag-Greenholt'),
  ('Considine Group'),
  ('Purdy, Zboncak and Willms'),
  ('Kiehn, Schiller and Kuhlman'),
  ('Anderson LLC'),
  ('Mante, Torp and Bartoletti'),
  ('Abbott-Fadel'),
  ('Hessel, Hauck and Stehr'),
  ('Conn-Abshire'),
  ('Stracke-Emard'),
  ('Wisoky, Steuber and Haley'),
  ('Frami LLC'),
  ('MacGyver LLC'),
  ('Toy, Moore and Miller'),
  ('Mraz-Rippin'),
  ('Harvey-Rosenbaum'),
  ('Wilderman-Kuhlman'),
  ('Pagac and Sons'),
  ('Kovacek, Kshlerin and Braun'),
  ('Mayer LLC'),
  ('Kohler, Dickens and Howe'),
  ('Hirthe Inc'),
  ('Rowe LLC'),
  ('Krajcik-Christiansen'),
  ('Paucek-Kulas'),
  ('Fay-Tillman'),
  ('Weimann-Reynolds'),
  ('Nolan LLC'),
  ('Conroy Inc'),
  ('Cartwright and Sons'),
  ('Predovic LLC'),
  ('Russel, Pfeffer and Moen'),
  ('Fisher-Larson'),
  ('Fay-Gutmann'),
  ('Johns, Treutel and Haag'),
  ('Schoen, Powlowski and Sporer'),
  ('Prohaska, Lehner and Labadie'),
  ('Schneider, Hyatt and Ferry'),
  ('Gottlieb and Sons'),
  ('Carter-Wisoky'),
  ('Krajcik-Schinner'),
  ('Ryan Inc'),
  ('Legros-Bauch'),
  ('Beatty and Sons'),
  ('Labadie LLC'),
  ('Fahey and Sons'),
  ('Schneider-Grimes'),
  ('Olson and Sons'),
  ('Graham, Spinka and Gorczany'),
  ('Blick and Sons'),
  ('Nolan-Nienow'),
  ('Hickle, Blanda and Reynolds'),
  ('Macejkovic-Weimann'),
  ('Collins Group'),
  ('Morar and Sons'),
  ('Hauck-Rohan'),
  ('Altenwerth, Douglas and Stroman'),
  ('Denesik, Kuhic and MacGyver'),
  ('King-Terry'),
  ('Luettgen, Treutel and Balistreri'),
  ('Koch and Sons'),
  ('Feest, Rowe and Witting'),
  ('Watsica, Kozey and Mills'),
  ('Gibson-Okuneva'),
  ('Lubowitz-Rosenbaum'),
  ('Kassulke-Emard'),
  ('Hackett, Friesen and Lockman'),
  ('Medhurst LLC'),
  ('Wolf-Rohan'),
  ('Zieme, Bartell and Miller'),
  ('Tillman, Kulas and Predovic'),
  ('Fadel Inc'),
  ('Towne, Wunsch and Spencer'),
  ('Dare-Marquardt'),
  ('Gislason, Pagac and Schuppe'),
  ('Witting-Effertz'),
  ('Rowe-Botsford'),
  ('Braun, Borer and Carter'),
  ('Weimann-Roob'),
  ('Abernathy, Farrell and Kozey'),
  ('Hagenes Group'),
  ('Farrell Group'),
  ('Metz-Kovacek'),
  ('Mitchell Inc'),
  ('Cassin-Shanahan'),
  ('Effertz, O. Reilly and King'),
  ('Beer, O. Reilly and Pouros'),
  ('Prohaska Group'),
  ('Kirlin Group'),
  ('Aufderhar Group'),
  ('Kuvalis, Adams and Block'),
  ('Pfannerstill-Schiller'),
  ('Jenkins and Sons'),
  ('Grady-Hauck'),
  ('Crist, Moen and Mayer'),
  ('Waters-Durgan'),
  ('Kuvalis, Nicolas and McDermott'),
  ('Quigley-Schiller'),
  ('Baumbach, Runolfsdottir and Cassin'),
  ('Veum, Nicolas and Hagenes'),
  ('Abbott-Mosciski'),
  ('Morar, Dickens and Fay'),
  ('Emard Group'),
  ('Bergstrom-Lubowitz'),
  ('O. Kon and Sons'),
  ('Schowalter-Padberg'),
  ('Yundt and Sons'),
  ('Stanton-Spencer'),
  ('Harris Inc'),
  ('Fisher, Effertz and Durgan'),
  ('Champlin-Murray'),
  ('Brekke Inc'),
  ('Gusikowski LLC'),
  ('Smitham LLC'),
  ('Robel-Boyle'),
  ('Stroman, Hudson and Watsica'),
  ('Spencer, Denesik and Jacobson'),
  ('Russel Group'),
  ('Schoen-Morar'),
  ('West Inc'),
  ('Wunsch LLC'),
  ('Wiza and Sons'),
  ('Doyle, McGlynn and Dach'),
  ('Gerlach-Mayer'),
  ('Marquardt-Fritsch'),
  ('Gleason-Ruecker'),
  ('Okuneva-Metz'),
  ('Bergnaum and Sons'),
  ('Wolff Group'),
  ('Heathcote-Schimmel'),
  ('Shields and Sons'),
  ('Schuster-Hermann'),
  ('Littel and Sons'),
  ('Stanton LLC'),
  ('Gottlieb-Fadel'),
  ('Rodriguez Inc'),
  ('Hoppe Group'),
  ('Renner, Langworth and Rath'),
  ('Murray-Wuckert'),
  ('Becker, Klocko and Bartell'),
  ('Sanford, Beer and Osinski'),
  ('Dickens and Sons'),
  ('Carroll, Kuhlman and Sipes'),
  ('McDermott, Effertz and Goldner'),
  ('Harris, Aufderhar and Murazik'),
  ('Russel-Murphy'),
  ('Paucek-Kessler'),
  ('Auer-Daniel'),
  ('Reilly-Predovic'),
  ('Corkery-Schinner'),
  ('Bernhard, Hyatt and Gaylord'),
  ('Runolfsson-Krajcik'),
  ('Boehm, Koss and Howe'),
  ('Langworth, Macejkovic and Predovic'),
  ('O. Conner, Kub and Kassulke'),
  ('Bayer-Price'),
  ('Bauch, Konopelski and Swaniawski'),
  ('Feil Inc'),
  ('Stark-Prosacco'),
  ('Carroll-Parisian'),
  ('Huels-Doyle'),
  ('Orn-Sawayn'),
  ('Donnelly-Fisher'),
  ('Weber-Corwin'),
  ('Mueller-Kerluke'),
  ('Schroeder-Kozey'),
  ('Wiza-Schiller'),
  ('Halvorson, Schinner and Mante'),
  ('Stark-Terry'),
  ('Casper LLC'),
  ('Ernser-Connelly'),
  ('Kemmer, Schinner and Pagac'),
  ('Hyatt LLC'),
  ('Mayer-Ferry'),
  ('Hahn Group'),
  ('Tremblay-Zieme'),
  ('Keeling, Auer and Schuster'),
  ('Grady-Fisher'),
  ('Wolf Group'),
  ('Reichel-Maggio'),
  ('Reichert, Bahringer and Halvorson'),
  ('Block Group'),
  ('Okuneva Inc'),
  ('Dibbert and Sons'),
  ('Borer-Bogisich'),
  ('Murazik, McLaughlin and Gibson'),
  ('Erdman LLC'),
  ('Boyle LLC'),
  ('Mitchell Inc'),
  ('Gottlieb-Strosin'),
  ('Doyle-Will'),
  ('Toy and Sons'),
  ('Bergnaum-Bahringer'),
  ('Raynor, Nicolas and Corwin'),
  ('Wolf LLC'),
  ('Hermiston, Rutherford and Kreiger'),
  ('Corwin-Bartoletti'),
  ('Price-Wilkinson'),
  ('Shanahan, Streich and Weissnat'),
  ('Halvorson and Sons'),
  ('Ruecker-Buckridge'),
  ('Schuppe and Sons'),
  ('Schuster Group'),
  ('Murray-D. Amore'),
  ('Parker-Boehm'),
  ('Franecki-Roberts'),
  ('Leffler Inc'),
  ('Donnelly-Gorczany'),
  ('Hammes, Corwin and Stokes'),
  ('Kozey-Jones'),
  ('Emmerich-Zemlak'),
  ('Weissnat, Kertzmann and Spinka'),
  ('MacGyver-Morar'),
  ('Moen Group'),
  ('Cremin Inc'),
  ('Robel Inc'),
  ('Zboncak-Lockman'),
  ('Gottlieb Inc'),
  ('Von and Sons'),
  ('Corwin-Weissnat'),
  ('Gaylord Inc'),
  ('Roob-Simonis'),
  ('Bayer-Crona'),
  ('Gulgowski-Hoeger'),
  ('Murazik, Nitzsche and Shields'),
  ('Balistreri-Glover'),
  ('Bins-Lowe'),
  ('Schowalter-Wyman'),
  ('Tremblay LLC'),
  ('Stroman LLC'),
  ('Herman-Kunde'),
  ('Gaylord-Wuckert'),
  ('Will and Sons'),
  ('Beahan-Homenick'),
  ('O. Reilly-Kuvalis'),
  ('Brown, Lueilwitz and Hintz'),
  ('Nikolaus-Stanton'),
  ('Gutmann, Medhurst and Beier'),
  ('Bartell, Walter and Jaskolski'),
  ('Maggio, McLaughlin and Hartmann'),
  ('Hermiston-Spencer'),
  ('Hegmann-Dibbert'),
  ('Reichert, Schmitt and Champlin'),
  ('Predovic-Heidenreich'),
  ('Gorczany-Schmitt'),
  ('Heathcote-Stehr'),
  ('McGlynn, Gutkowski and Huels'),
  ('O. Connell-Miller'),
  ('Effertz, Stoltenberg and Zieme'),
  ('Okuneva-Reinger'),
  ('Gibson-Klocko'),
  ('Gleason-Rohan'),
  ('Zboncak, Satterfield and Von'),
  ('Powlowski-Wilkinson'),
  ('Brown-Gorczany'),
  ('Gutmann, Schneider and Labadie'),
  ('Cummings-Jenkins'),
  ('Funk, Rath and Jacobi'),
  ('Gleichner LLC'),
  ('Bogisich and Sons'),
  ('Schulist Inc'),
  ('West-Schulist'),
  ('Gerlach, Ziemann and Lubowitz'),
  ('Crooks-Weimann'),
  ('Koelpin Group'),
  ('Corwin Inc'),
  ('Pacocha-Russel'),
  ('Ward Group'),
  ('Pfeffer-Dooley'),
  ('Farrell, Fritsch and Lehner'),
  ('Stehr-Fahey'),
  ('Homenick, Bayer and Huels'),
  ('Flatley-Stamm'),
  ('Smith, Abernathy and Ward'),
  ('Robel, King and Runolfsdottir'),
  ('Maggio-Predovic'),
  ('Nitzsche LLC'),
  ('Ankunding and Sons'),
  ('Hackett, Jacobson and Paucek'),
  ('Brown, Brown and Dare'),
  ('Prohaska and Sons'),
  ('Hyatt, Effertz and Smitham'),
  ('Romaguera Inc'),
  ('Koelpin, Huels and Beahan'),
  ('Boyle-Reichert'),
  ('Feil, Ruecker and Wolf'),
  ('Ledner-Durgan'),
  ('Stehr-Hane'),
  ('Howell, Kautzer and Mitchell'),
  ('Dare Inc'),
  ('Rohan and Sons'),
  ('Wiegand Group'),
  ('Hoeger-Mayer'),
  ('Murazik, Johnson and Green'),
  ('Prosacco and Sons'),
  ('Osinski-Heaney'),
  ('Fay, Altenwerth and Koepp'),
  ('Schroeder-Conn'),
  ('Shields Inc'),
  ('Herman Inc'),
  ('Lueilwitz-Carroll'),
  ('Collier Group'),
  ('Emard-Little'),
  ('Carter LLC'),
  ('Fisher, Corwin and Jaskolski'),
  ('Jerde Group'),
  ('Douglas-Koepp'),
  ('Altenwerth, Schimmel and Bergnaum'),
  ('Larkin LLC'),
  ('Cole-Bayer'),
  ('Rempel, Gorczany and Graham'),
  ('Murazik, Stroman and Heaney'),
  ('Bode, Keebler and Dare'),
  ('Bradtke-Weber'),
  ('Schaden-Hegmann'),
  ('Schmeler, Douglas and Casper'),
  ('Crist Inc'),
  ('Nicolas, Schoen and Smith'),
  ('Schiller-Ankunding'),
  ('Kuvalis-Pollich'),
  ('Stroman-Howe'),
  ('Kohler Group'),
  ('Breitenberg LLC'),
  ('DuBuque-Thompson'),
  ('Jones Inc'),
  ('O. Connell and Sons'),
  ('Stanton Group'),
  ('Welch and Sons'),
  ('Flatley-Veum'),
  ('Dickens LLC'),
  ('Langworth Group'),
  ('Ankunding-Marvin'),
  ('Sporer LLC'),
  ('Wolf Inc'),
  ('Wilderman Group'),
  ('Hoeger-Langosh'),
  ('Gutkowski, Langworth and Huel'),
  ('Parisian, Parisian and Casper'),
  ('Greenfelder, Simonis and Schinner'),
  ('DuBuque LLC'),
  ('Pacocha Inc'),
  ('Hickle, Ratke and Klocko'),
  ('Willms and Sons'),
  ('Swaniawski and Sons'),
  ('Russel-Kunde'),
  ('Torphy-Johns'),
  ('Prohaska, Balistreri and Kassulke'),
  ('Wuckert Group'),
  ('Cronin-Hammes'),
  ('Pfannerstill Group'),
  ('McCullough-Armstrong'),
  ('Bartoletti Inc'),
  ('Bergstrom Inc'),
  ('Hilll, Stracke and Becker'),
  ('Emard and Sons'),
  ('Roob LLC'),
  ('Mayert and Sons'),
  ('Dach and Sons'),
  ('Feil-Torphy'),
  ('Dietrich Group'),
  ('Hettinger LLC'),
  ('Kshlerin Group'),
  ('Lakin Group'),
  ('Christiansen, Douglas and Ratke'),
  ('Mohr Group'),
  ('Harber Group'),
  ('Schmidt, Heidenreich and Runolfsson'),
  ('Schmitt-Towne'),
  ('Flatley, Kertzmann and Block'),
  ('Fahey, Larkin and Roob'),
  ('Cassin, Robel and Kuvalis'),
  ('Mayer, Ledner and Moore'),
  ('Treutel, Parker and Hettinger'),
  ('Bechtelar, Schaden and Wunsch'),
  ('Howell Inc'),
  ('Ritchie Group'),
  ('Stracke and Sons'),
  ('Halvorson LLC'),
  ('Schaden and Sons'),
  ('Smitham, Schmeler and Koelpin'),
  ('Hamill-Ziemann'),
  ('Mraz Inc'),
  ('Moen-Kessler'),
  ('Thiel-Klocko'),
  ('Dibbert, Johns and Bahringer'),
  ('Hauck Group'),
  ('Gibson-Terry'),
  ('Becker-Keebler'),
  ('McClure Group'),
  ('Tremblay, Veum and Pfannerstill'),
  ('Pouros LLC'),
  ('Bartell Inc'),
  ('Jaskolski, Stoltenberg and Okuneva'),
  ('Ullrich and Sons'),
  ('Erdman Group'),
  ('Tremblay-Carroll'),
  ('Grimes-Ferry'),
  ('Nitzsche, O. Keefe and Ferry'),
  ('Koss-Kuvalis'),
  ('Goodwin-Trantow'),
  ('Rodriguez and Sons'),
  ('Larkin, Dare and Schiller'),
  ('Gulgowski Inc'),
  ('Gorczany Group'),
  ('Robel, Grimes and Ratke'),
  ('Reichel Inc'),
  ('Stracke, Cole and Hahn'),
  ('Treutel-Purdy'),
  ('Hilll LLC'),
  ('Dietrich-Klocko'),
  ('Smith, Johnson and Kozey'),
  ('Hessel-Friesen'),
  ('Hills-Effertz'),
  ('Dickens, Schmitt and Rutherford'),
  ('Monahan, Will and Fisher'),
  ('Yundt-Daugherty'),
  ('Graham, Dare and O. Connell'),
  ('Hamill Group'),
  ('Morar and Sons'),
  ('Towne, Mitchell and Yundt'),
  ('Schumm, Shields and Schuppe'),
  ('Stracke, Dibbert and Bogan'),
  ('Hahn-Wilderman'),
  ('Morar, Maggio and Baumbach'),
  ('Mitchell-Weimann'),
  ('Koch-Kulas'),
  ('Bosco-Wilkinson'),
  ('Dibbert, Braun and Nader'),
  ('Rodriguez, Stroman and Huels'),
  ('Mann, Ullrich and McLaughlin'),
  ('Hansen, Will and Huel'),
  ('Paucek, Kassulke and Moen'),
  ('Quigley-Hilpert'),
  ('Herman LLC'),
  ('Schoen, Miller and Christiansen'),
  ('Spinka LLC'),
  ('Stamm-Rath'),
  ('Little, McDermott and Beahan'),
  ('Lakin LLC'),
  ('Schowalter and Sons'),
  ('Gutmann, Conroy and Lockman'),
  ('Roob LLC'),
  ('Daniel-Crooks'),
  ('Mayer, Mante and Rohan'),
  ('Towne and Sons'),
  ('Kuhlman-Buckridge'),
  ('Abernathy, Waters and Will'),
  ('Parker-Grant'),
  ('Klocko, Connelly and Stamm'),
  ('Breitenberg-Koss'),
  ('Kohler, Satterfield and Murphy'),
  ('Schumm, Robel and Treutel'),
  ('Luettgen-Koepp'),
  ('Waters LLC'),
  ('Weissnat, Schinner and O. Hara'),
  ('Mayert, Boehm and McKenzie'),
  ('Hagenes, Olson and Crooks'),
  ('Ondricka-Bergstrom'),
  ('Fay, Barrows and Jast'),
  ('Yost-Hauck'),
  ('Hoppe Inc'),
  ('Pouros-Haag'),
  ('Renner-Kuhn'),
  ('Feest-Nienow'),
  ('Herzog and Sons'),
  ('Rutherford Group'),
  ('O. Kon-Hermiston'),
  ('Pfeffer, Price and Turcotte'),
  ('Kuhlman-Luettgen'),
  ('Tromp-Hickle'),
  ('Daugherty-Mertz'),
  ('Stoltenberg, Bartell and Hilpert'),
  ('McCullough-Hane'),
  ('Pollich, Abbott and Terry'),
  ('Yundt-Wiza'),
  ('Harris, Gaylord and Bruen'),
  ('Olson and Sons'),
  ('Bins LLC'),
  ('West and Sons'),
  ('Lesch, Hagenes and Schiller'),
  ('Boyer Inc'),
  ('Jakubowski-Miller'),
  ('Fahey, Wyman and Streich'),
  ('Reinger, Von and Erdman'),
  ('O. Kon, Robel and Dibbert'),
  ('Weissnat, Lockman and Kris'),
  ('McCullough and Sons'),
  ('Fadel LLC'),
  ('Funk-Gibson'),
  ('Jerde-Bode'),
  ('Wintheiser-Schinner'),
  ('Kreiger-Abbott'),
  ('Shanahan-Hettinger'),
  ('Bosco-Sawayn'),
  ('Harris, Kunde and Armstrong'),
  ('Hand Group'),
  ('Dibbert, Konopelski and Hilll'),
  ('Stiedemann-Simonis'),
  ('Treutel Inc'),
  ('O. Reilly LLC'),
  ('Kautzer-Kreiger'),
  ('Klocko Group'),
  ('Crona-Nicolas'),
  ('Ritchie and Sons'),
  ('Willms, Gulgowski and Gleichner'),
  ('Hayes Inc'),
  ('Heathcote-Sawayn'),
  ('Durgan, Walker and Murazik'),
  ('Schuppe and Sons'),
  ('Kihn and Sons'),
  ('Littel, Kreiger and Osinski'),
  ('Dach-Conroy'),
  ('Rempel-Stokes'),
  ('Schmitt-Shanahan'),
  ('Reichel Group'),
  ('Lang Inc'),
  ('Koss, Wolff and Collins'),
  ('Bergnaum and Sons');


--
-- Table structure for table rubro_presupuestal
--

DROP TABLE IF EXISTS rubro_presupuestal;
CREATE TABLE rubro_presupuestal (
  id_rubro int NOT NULL IDENTITY,
  nombre varchar(80) NOT NULL,
  presupuesto float NOT NULL,
  PRIMARY KEY (id_rubro)
);

--
-- Dumping data for table rubro_presupuestal
--

INSERT INTO rubro_presupuestal(nombre, presupuesto) VALUES 
  ('Materiales de oficina',10500),
  ('Materiales de almacen',20000);


--
-- Table structure for table salida
--

DROP TABLE IF EXISTS salida;
CREATE TABLE salida (
  nro_salida int NOT NULL IDENTITY,
  fecha_salida datetime NOT NULL,
  fecha_entrega datetime NOT NULL,
  PRIMARY KEY (nro_salida)
);

--
-- Table structure for table estado_documento
--

DROP TABLE IF EXISTS estado_documento;
CREATE TABLE estado_documento (
  id_estado_documento int NOT NULL IDENTITY,
  nombre varchar(80) NULL,
  PRIMARY KEY (id_estado_documento)
);

--
-- Dumping data for table estado_documento
--

INSERT INTO estado_documento (nombre) VALUES 
  ('Aprobado'),
  ('Enviado'),
  ('Procesado'),
  ('Recibido');


--
-- Table structure for table area
--
DROP TABLE IF EXISTS area;
CREATE TABLE area (
  id_area int NOT NULL IDENTITY,
  nombre varchar(80)  NOT NULL,
  id_personal int NOT NULL,
  id_area_superior int DEFAULT NULL,
  PRIMARY KEY (id_area),
  CONSTRAINT fk_area_personal FOREIGN KEY (id_personal) REFERENCES personal (id_personal)
);

--
-- Dumping data for table area
--

INSERT INTO area(nombre, id_personal, id_area_superior) VALUES 
  ('Asamblea Universitaria',1,1),
  ('Comité Electoral',1,1),
  ('Tribunal de Honor',1,1),
  ('Defensoría Universitaria',1,1),
  ('Consejo Universitario',1,1),
  ('Rectorado',1,5),
  ('Órgano de Control Institucional',1,6),
  ('Comisión Permanente de Fiscalización',1,6),
  ('Consejo Consultivo de la Alta Dirección',1,6),
  ('Dirección de Informática',1,6),
  ('Dirección del Museo Regional Leoncio Prado',1,6),
  ('Dirección Universitaria de Planificación y Presupuesto',1,6),
  ('Dirección de Calidad y Acreditación Universitaria',1,6),
  ('Dirección de Cooperación Técnica Internacional',1,6),
  ('Dirección de Imagen Institucional',1,6),
  ('Secretaria General',1,6),
  ('Oficina de Asesoría Legal',1,6),
  ('Dirección General de Administración',1,6),
  ('Vice Rectorado Académico',1,6),
  ('Vice Rectorado de Investigación',1,6),
  ('Consejo de Facultad',1,6),
  ('Escuela de Posgrado',1,6),
  ('Fundación UNHEVAL',1,6),
  ('Unidad de Estadística',1,10),
  ('Unidad de Telecomunicaciones',1,10),
  ('Unidad de Desarrollo de Sistema',1,10),
  ('Unidad de Soporte Técnico y Virtual',1,10),
  ('Unidad de Transparencia',1,10),
  ('Oficina del Museo Regional de Leoncio Prado',1,11),
  ('Unidad de Gestión Cultural: Historia, Arqueología e Investigación',1,29),
  ('Unidad de Promoción y Difusión',1,29),
  ('Unidad de Grados y Títulos',1,16),
  ('Unidad de Archivo Central',1,16),
  ('Unidad de trámite documentario',1,16),
  ('Unidad de Asuntos Administrativos',1,17),
  ('Unidad de Procesos Judiciales',1,17),
  ('Oficina de Programación e Inversiones',1,12),
  ('Oficina de Planificación y Presupuesto',1,12),
  ('Unidad de Planeamiento Estratégico',1,38),
  ('Unidad de Racionalización',1,38),
  ('Unidad de Presupuesto',1,38),
  ('Unidad de Estudios, y proyectos de Desarrollo',1,38),
  ('Oficina de Calidad y Acreditación',1,13),
  ('Unidad de Sistemas de Calidad e Información',1,43),
  ('Unidad de Acreditación y Mejora Continua',1,43),
  ('Unidad de Licenciamiento',1,43),
  ('Oficina de Cooperación Técnica Internacional',1,14),
  ('Unidad de Becas y Movilidad Académica Nacional e Internacional',1,47),
  ('Unidad de Convenios y bolsa de Trabajo',1,47),
  ('Unidad de Comunicación',1,15),
  ('Unidad de Relaciones Públicas',1,15),
  ('Oficina de Recursos Humanos',1,18),
  ('Oficina de Logística',1,18),
  ('Oficina de Contabilidad',1,18),
  ('Oficina de Tesorería',1,18),
  ('Oficina de Infraestructura y Mantenimiento',1,18),
  ('Oficina de Administración, Patrimonio y Operaciones de la UNHEVAL',1,18),
  ('Oficina Central de los Centros Generadores de BB Y SS de la UNHEVAL',1,18),
  ('Secretaría técnica',1,52),
  ('Unidad de Escalafón y Control',1,52),
  ('Unidad de Remuneraciones, Pensiones y Compensaciones',1,52),
  ('Unidad de Procesos y Contrataciones',1,53),
  ('Unidad de Servicios Auxiliares',1,53),
  ('Unidad de Adquisiciones',1,53),
  ('Unidad de Almacén',1,53),
  ('Unidad de Contabilidad Presupuestal',1,54),
  ('Unidad de Integración Contable',1,54),
  ('Unidad de Costos y Tributación',1,54),
  ('Unidad de Ingresos',1,55),
  ('Unidad de Egresos',1,55),
  ('Unidad de Estudios, Supervisión y Liquidación de Obras',1,56),
  ('Unidad de Ejecución de Obras y Mantenimiento',1,56),
  ('Unidad de Administración Financiera y Contable',1,56),
  ('Unidad de Bienes Patrimoniales',1,57),
  ('Unidad de Transporte',1,57),
  ('Unidad de Administración de la Ciudad Universitaria y Locales de la UNHEVAL',1,57),
  ('Dirección de Asuntos y Servicios Académicos',1,19),
  ('Dirección de Bienestar Universitario',1,19),
  ('Dirección de Admisión',1,19),
  ('Dirección de Responsabilidad Social Universitaria',1,19),
  ('Dirección de Biblioteca Central',1,19),
  ('Dirección de Educación a Distancia y Formación Continua',1,19),
  ('Oficina de Desarrollo Académico',1,77),
  ('Oficina de Evaluación Académica',1,77),
  ('Unidad de Procesos Académicos',1,83),
  ('Unidad de Registro Central y Archivo Académico',1,83),
  ('Programa de Capacitación y Titulación Profesional (PROCATP)',1,83),
  ('Centro Preuniversitario Valdizano (CEPREVAL)',1,83),
  ('Unidad Editorial Universitaria',1,83),
  ('Unidad de Centro de Idiomas',1,83),
  ('Unidad de Laboratorios',1,83),
  ('Unidad de Desarrollo y Perfecciona miento Profesional',1,84),
  ('Unidad de Gestión Curricular',1,84),
  ('Unidad de Seguimiento al Egresado',1,84),
  ('Oficina de Bienestar Universitario',1,78),
  ('Unidad de Actividad Física y Mental',1,95),
  ('Unidad de Formación Cultural',1,95),
  ('Unidad de Servicios Universitarios',1,95),
  ('Oficina de Admisión',1,79),
  ('Oficina de Responsabilidad Social Universitaria',1,80),
  ('Unidad de Extensión Cultural',1,100),
  ('Unidad de Proyección Social',1,100),
  ('Unidad de Formulación, Seguimiento y Evaluación de Programas y Proyectos',1,100),
  ('Oficina de Biblioteca Central',1,81),
  ('Unidad de Desarrollo Tecnológico',1,104),
  ('Unidad de Gestión de la Colección',1,104),
  ('Unidad de Repositorio Institucional',1,104),
  ('Unidad de Organización y Análisis de la Información',1,104),
  ('Unidad de Servicios Bibliográfico',1,104),
  ('Oficina de Educación a Distancia y Formación Continua',1,82),
  ('Unidad Centro de estudios Informáticos',1,110),
  ('Unidad de Desarrollo de Educación a Distancia y formación Continua',1,110),
  ('Consejo de Investigación',1,20),
  ('Dirección de Investigación Universitaria',1,20),
  ('Dirección de Gestión de Investigación',1,20),
  ('Dirección de Transferencia e Innovación',1,20),
  ('Dirección del Centro de Producción de Bienes y Servicios',1,20),
  ('Comité de ética de Investigación',1,114),
  ('Oficina de Investigación Universitaria',1,114),
  ('Instituto de Investigación Cs. de la Salud',1,119),
  ('Instituto de Investigación Cs. Agropecuarias',1,119),
  ('Instituto de Investigación de Ingenierías',1,119),
  ('Instituto de Investigación de Cs. Sociales',1,119),
  ('Instituto de Investigación de Cs. Pedagógicas',1,119),
  ('Oficina de Planeamiento y Gestión',1,115),
  ('Oficina de Transferencia, Emprendimiento e Innovación',1,116),
  ('Unidad de Oferta Tecnológica',1,116),
  ('Unidad de Propiedad Intelectual, Patentes y Publicaciones',1,116),
  ('Unidad de Emprendimiento e Incubadora de Empresas',1,116),
  ('Oficina del Centro de Producción de Bienes y Servicios',1,117),
  ('Centro de Producción e Investigación Pecuaria de Kotosh',1,130),
  ('Centro de Producción, Investigación y Experimentación de Canchan y Conobamba',1,130),
  ('Centro de Producción, Investigación y Experimentación Llullapichis',1,130),
  ('Centro Recreacional de Kotosh',1,130),
  ('Facultad de Ciencias Agrarias',1,21),
  ('Facultad de Ciencias Administrativas y Turismo',1,21),
  ('Facultad de Ciencias Contables y Financieras',1,21),
  ('Facultad de Derecho y Ciencias Poléticas',1,21),
  ('Facultad de Economía',1,21),
  ('Facultad de Ciencias de la Educación',1,21),
  ('Facultad de Enfermería',1,21),
  ('Facultad de Ingeniería y Arquitectura',1,21),
  ('Facultad de Industrial y Sistemas',1,21),
  ('Facultad de Medicina',1,21),
  ('Facultad de Medicina Veterinaria y Zootecnia',1,21),
  ('Facultad de Psicología',1,21),
  ('Facultad de Obstetricia',1,21),
  ('Facultad de Ciencias Sociales',1,21),
  ('Consejo Directivo de la Escuela Postgrado',1,22);

--
-- Table structure for table documento
--
DROP TABLE IF EXISTS documento;
CREATE TABLE documento (
  id_documento int NOT NULL,
  nombre varchar(50)  NOT NULL,
  PRIMARY KEY (id_documento),
  CONSTRAINT uk_id_documento UNIQUE (id_documento),
  CONSTRAINT uk_nombre UNIQUE (nombre)
);

--
-- Dumping data for table documento
--

INSERT INTO documento VALUES 
  (1,'Solicitud'),
  (2,'Orden de compra'),
  (3,'Factura');

--
-- Table structure for table documento_autorizacion
--

DROP TABLE IF EXISTS documento_autorizacion;
CREATE TABLE documento_autorizacion (
  id_autorizacion int NOT NULL,
  id_documento int NOT NULL,
  CONSTRAINT fk_documento_autorizacion_autorizacion FOREIGN KEY (id_autorizacion) REFERENCES autorizacion (id_autorizacion),
  CONSTRAINT fk_documento_autorizacion_documento FOREIGN KEY (id_documento) REFERENCES documento (id_documento)
);

--
-- Table structure for table orden_compra
--

DROP TABLE IF EXISTS orden_compra;
CREATE TABLE orden_compra (
  nro_orden int NOT NULL IDENTITY,
  id_documento int NOT NULL,
  valor_total float NOT NULL DEFAULT '0',
  fecha_creacion datetime NOT NULL,
  fecha_entrega datetime NOT NULL,
  id_estado_documento int NOT NULL,
  PRIMARY KEY (nro_orden),
  CONSTRAINT fk_orden_compra_documento FOREIGN KEY (id_documento) REFERENCES documento (id_documento),
  CONSTRAINT fk_orden_compra_estado_documento FOREIGN KEY (id_estado_documento) REFERENCES estado_documento (id_estado_documento)
);

--
-- Table structure for table tipo_item
--

DROP TABLE IF EXISTS tipo_item;
CREATE TABLE tipo_item (
  id_tipo_item int NOT NULL IDENTITY,
  nombre varchar(80)  NOT NULL,
  PRIMARY KEY (id_tipo_item)
);

--
-- Dumping data for table tipo_item
--

INSERT INTO tipo_item(nombre) VALUES 
  ('suministro'),
  ('inmueble');

--
-- Table structure for table item
--

DROP TABLE IF EXISTS item;
CREATE TABLE item (
  id_item int NOT NULL IDENTITY,
  id_tipo_item int NOT NULL,
  nombre varchar(80)  NOT NULL,
  unidad_medida varchar(40)  NOT NULL,
  PRIMARY KEY (id_item),
  CONSTRAINT fk_item_tipo_item FOREIGN KEY (id_tipo_item) REFERENCES tipo_item (id_tipo_item)
);

--
-- Dumping data for table item
--

INSERT INTO item VALUES 
  (1,'Millar papel bond','gramos'),
  (1,'Pantalla de computadora','unidades'),
  (1,'Bolígrado L-036 Caja X 10','unidades'),
  (1,'Silla giratoria','unidades'),
  (1,'Escritorios','unidades'),
  (1,'Impresora','unidades'),
  (1,'Engrapadoras','unidades'),
  (1,'Caja de grapas 26/6 X 5000 ','unidades');

--
-- Table structure for table cotizacion
--

DROP TABLE IF EXISTS cotizacion;
CREATE TABLE cotizacion (
  id_cotizacion int NOT NULL IDENTITY,
  id_item int NOT NULL,
  id_proveedor int NOT NULL,
  valor_unitario float NOT NULL,
  PRIMARY KEY (id_cotizacion),
  CONSTRAINT fk_cotizacion_item FOREIGN KEY (id_item) REFERENCES item (id_item),
  CONSTRAINT fk_cotizacion_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedor (id_proveedor)
);

--
-- Dumping data for table cotizacion
--

INSERT INTO cotizacion (id_item, id_proveedor, valor_unitario) VALUES 
  (2,34,42.58),
  (8,21,1.07),
  (3,53,6.93),
  (6,5,97.2),
  (5,13,190.26),
  (5,86,8.17),
  (8,86,124.91),
  (3,74,140.12),
  (3,55,156.09),
  (4,17,156.04),
  (8,4,140.96),
  (2,50,121.98),
  (5,10,196.79),
  (5,50,45.93),
  (1,54,7.11),
  (6,64,158.91),
  (4,19,180.51),
  (1,100,32.83),
  (4,66,90.15),
  (3,46,175.02),
  (1,14,162.43),
  (6,26,95.06),
  (6,99,157.99),
  (8,72,59.07),
  (6,35,69.72),
  (4,20,132.62),
  (6,72,146.7),
  (2,69,114.34),
  (8,67,58.41),
  (1,21,181.66),
  (3,5,172.37),
  (3,6,82.91),
  (7,96,92.5),
  (6,61,94.23),
  (6,63,184.18),
  (7,100,193.78),
  (8,78,128.53),
  (2,41,177.26),
  (2,92,67.41),
  (2,76,65.72),
  (6,25,55.73),
  (1,74,99.08),
  (3,80,107.07),
  (3,45,75.04),
  (7,65,16.44),
  (4,56,169.8),
  (8,87,58.42),
  (7,56,64.24),
  (3,65,98.08),
  (8,50,37.89),
  (3,52,64.13),
  (5,25,137.75),
  (7,74,8.56),
  (4,28,41.14),
  (4,70,63.43),
  (8,14,115.97),
  (3,86,84.56),
  (7,58,112.44),
  (7,31,108.73),
  (6,23,79.51),
  (4,27,148.33),
  (1,43,70.17),
  (4,24,70.94),
  (7,3,131.19),
  (7,63,185.23),
  (8,66,98.06),
  (4,40,28.53),
  (3,99,57.84),
  (5,61,145.03),
  (7,25,76.07),
  (7,26,88.31),
  (7,70,60.51),
  (2,72,92.13),
  (1,45,119.42),
  (1,46,97.02),
  (6,48,162.92),
  (6,64,132.02),
  (4,64,41.29),
  (3,98,184.97),
  (7,65,26.1),
  (6,11,21.16),
  (7,3,3.41),
  (1,67,76.52),
  (3,17,195),
  (8,26,150.99),
  (2,78,45.64),
  (5,20,128.58),
  (2,10,165.94),
  (8,94,33.15),
  (5,91,173.73),
  (6,40,5.14),
  (1,13,171.11),
  (2,68,28.09),
  (5,47,69.01),
  (7,59,94.49),
  (2,5,168.34),
  (4,72,66.28),
  (7,10,137.47),
  (6,63,158.6),
  (2,59,59.64);


--
-- Table structure for table solicitud
--

DROP TABLE IF EXISTS solicitud;
CREATE TABLE solicitud (
  nro_solicitud int NOT NULL IDENTITY,
  id_documento int NOT NULL DEFAULT '1',
  id_rubro int NOT NULL,
  id_area int NOT NULL,
  valor_total float NOT NULL DEFAULT '0',
  fecha_creacion datetime NOT NULL,
  id_estado_documento int NOT NULL,
  PRIMARY KEY (nro_solicitud),
  CONSTRAINT fk_solicitud_area FOREIGN KEY (id_area) REFERENCES area (id_area),
  CONSTRAINT fk_solicitud_documento FOREIGN KEY (id_documento) REFERENCES documento (id_documento),
  CONSTRAINT fk_solicitud_estado_documento FOREIGN KEY (id_estado_documento) REFERENCES estado_documento (id_estado_documento),
  CONSTRAINT fk_solicitud_rubro_presupuestal FOREIGN KEY (id_rubro) REFERENCES rubro_presupuestal (id_rubro)
);

--
-- Dumping data for table solicitud
--

INSERT INTO solicitud(id_rubro, id_area, valor_total, fecha_creacion, id_estado_documento) VALUES 
  (1,1,0,'20-04-22 10:00:00',3),
  (1,2,0,'28-02-22 11:23:00',3),
  (1,1,0,'15-02-22 13:23:20',3),
  (1,3,0,'11-04-22 09:20:00',3);

--
-- Table structure for table factura
--

DROP TABLE IF EXISTS factura;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE factura (
  nro_entrada_factura int NOT NULL IDENTITY,
  fecha_facturacion datetime NOT NULL,
  nro_factura int NOT NULL,
  nro_orden int NOT NULL,
  total_items decimal(10,0) DEFAULT NULL,
  valor_total float NOT NULL DEFAULT '0',
  id_proveedor int NOT NULL,
  PRIMARY KEY (nro_entrada_factura),
  CONSTRAINT fk_factura_orden_compra FOREIGN KEY (nro_orden) REFERENCES orden_compra (nro_orden),
  CONSTRAINT fk_factura_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedor (id_proveedor)
);

--
-- Table structure for table factura_detalle
--

DROP TABLE IF EXISTS factura_detalle;
CREATE TABLE factura_detalle (
  id_factura_detalle int NOT NULL IDENTITY,
  nro_entrada_factura int NOT NULL,
  id_cotizacion int NOT NULL,
  cantidad_entregada decimal(10,0) NOT NULL,
  PRIMARY KEY (id_factura_detalle),
  CONSTRAINT fk_factura_detalle_cotizacion FOREIGN KEY (id_cotizacion) REFERENCES cotizacion (id_cotizacion),
  CONSTRAINT fk_factura_detalle_factura FOREIGN KEY (nro_entrada_factura) REFERENCES factura (nro_entrada_factura)
);

--
-- Table structure for table solicitud_detalle
--
DROP TABLE IF EXISTS solicitud_detalle;
CREATE TABLE solicitud_detalle (
  id_solicitud_detalle int NOT NULL IDENTITY,
  nro_solicitud int NOT NULL,
  id_item int NOT NULL,
  cantidad_requerida decimal(10,0) NOT NULL,
  valor_total float NOT NULL DEFAULT '0',
  PRIMARY KEY (id_solicitud_detalle),
  CONSTRAINT fk_solicitud_detalle_item FOREIGN KEY (id_item) REFERENCES item (id_item),
  CONSTRAINT fk_solicitud_detalle_solicitud FOREIGN KEY (nro_solicitud) REFERENCES solicitud (nro_solicitud)
);

--
-- Dumping data for table solicitud_detalle
--

INSERT INTO solicitud_detalle(nro_solicitud, id_item, cantidad_requerida, valor_total) VALUES 
  (1,1,20,0),
  (1,2,2,0),
  (2,3,30,0),
  (1,4,5,0),
  (3,1,15,0),
  (2,2,3,0),
  (4,3,20,0),
  (2,4,2,0);

--
-- Table structure for table salida_detalle
--

DROP TABLE IF EXISTS salida_detalle;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE salida_detalle (
  id_salida_detalle int NOT NULL IDENTITY,
  nro_salida int NOT NULL,
  id_personal int NOT NULL,
  id_item int NOT NULL,
  cantidad_despachada decimal(10,0) NOT NULL,
  codigo_ubicacion varchar(12)  NOT NULL,
  PRIMARY KEY (id_salida_detalle),
  CONSTRAINT fk_salida_detalle_item FOREIGN KEY (id_item) REFERENCES item (id_item),
  CONSTRAINT fk_salida_detalle_personal FOREIGN KEY (id_personal) REFERENCES personal (id_personal),
  CONSTRAINT fk_salida_detalle_salida FOREIGN KEY (nro_salida) REFERENCES salida (nro_salida)
);

--
-- Table structure for table entrada_salida
--
DROP TABLE IF EXISTS entrada_salida;
CREATE TABLE entrada_salida (
  id_factura_detalle int NOT NULL,
  id_salida_detalle int NOT NULL,
  CONSTRAINT fk_entrada_salida_factura_detalle FOREIGN KEY (id_factura_detalle) REFERENCES factura_detalle (id_factura_detalle),
  CONSTRAINT fk_entrada_salida_salida_detalle FOREIGN KEY (id_salida_detalle) REFERENCES salida_detalle (id_salida_detalle)
);

--
-- Table structure for table orden_compra_detalle
--

DROP TABLE IF EXISTS orden_compra_detalle;
CREATE TABLE orden_compra_detalle (
  id_orden_compra_detalle int NOT NULL IDENTITY,
  nro_orden int NOT NULL,
  id_cotizacion int NOT NULL,
  id_solicitud_detalle int NOT NULL,
  cantidad_solicitada decimal(10,0) NOT NULL,
  valor_total float NOT NULL DEFAULT '0',
  PRIMARY KEY (id_orden_compra_detalle),
  CONSTRAINT fk_orden_compra_detalle_cotizacion FOREIGN KEY (id_cotizacion) REFERENCES cotizacion (id_cotizacion),
  CONSTRAINT fk_orden_compra_detalle_orden_compra FOREIGN KEY (nro_orden) REFERENCES orden_compra (nro_orden),
  CONSTRAINT fk_orden_compra_detalle_solicitud_detalle FOREIGN KEY (id_solicitud_detalle) REFERENCES solicitud_detalle (id_solicitud_detalle)
);

--
-- Table structure for table solicitud_orden_detalle
--

DROP TABLE IF EXISTS solicitud_orden_detalle;
CREATE TABLE solicitud_orden_detalle (
  id_solicitud_orden_detalle int NOT NULL IDENTITY,
  id_solicitud_detalle int DEFAULT NULL,
  id_orden_compra_detalle int DEFAULT NULL,
  PRIMARY KEY (id_solicitud_orden_detalle),
  CONSTRAINT fk_sod_orden_comprar_detalle FOREIGN KEY (id_orden_compra_detalle) REFERENCES orden_compra_detalle (id_orden_compra_detalle),
  CONSTRAINT fk_sod_solicitud_detalle FOREIGN KEY (id_solicitud_detalle) REFERENCES solicitud_detalle (id_solicitud_detalle)
);
